config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  devise_for :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  get 'landing', to:"home#landing"
  get 'leave', to:"home#leave"





  #admin_routes
  get 'adminhome', to:"admin#adminhome"
  get 'employeemanagement', to: "admin#employeemanagement"
  
  
  get 'adminhome', to:"admin#adminhome"
  post 'leaveform', to: "admin#create"
  get 'leaveform', to:"admin#leaveform"
  
  get 'designationmanagement', to: "designation#designationmanagement"
  get 'designationform', to: "designation#designationform"
  post 'designationform', to: "designation#create"
 
  get 'projectmanagement', to: "project#projectmanagement"
  get 'projectform', to: "project#projectform"
  post 'projectform' ,to: "project#create"
  

  get 'holidaysmanagement', to: "holiday#holidaysmanagement"
  get 'holidaysform', to: "holiday#holidaysform"
  post 'holidaysform', to: "holiday#create"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/designation.rb
class Designation < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
end

app/models/employee_leave.rb
class EmployeeLeave < ApplicationRecord
end

app/models/employees_project.rb
class EmployeesProject < ApplicationRecord
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave.rb
class Leave < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/projects_management.rb
class ProjectsManagement < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new
    @leaves = Leave.new
  end
  def create
    @leaves= Leave.new(leavesparams)
    @leaves.save
    #render plain: @leaves.errors.inspect
    redirect_to adminhome_path
  end
  def leavesparams
    params.permit(:name , :description)
  end

  def employeemanagement
    @employees=Employee.all
  end
  def adminhome
    @leave = Leave.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def landing
    $name = full_name
    $pname = profile_name
  end

  
  def full_name
    user=Employee.find(current_employee.id)
    first_name = user.first_name
    last_name = user.last_name
    return first_name.capitalize+" "+last_name.capitalize
  end
  def profile_name
    user=Employee.find(current_employee.id)
    first_name = user.first_name
    last_name = user.last_name
    return first_name[0].capitalize+last_name[0].capitalize
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designation_helper.rb
module DesignationHelper
end

app/helpers/holiday_helper.rb
module HolidayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/admin/_adminmenu.html.erb
<div class="left-container">
    <div class="left-button">
    <%= button_to "Leave", adminhome_path, method: :get,:class => "menu-buttons" %>
    </div>
    <div class="left-button">
    <%= button_to "Holiday", holidaysmanagement_path, method: :get,:class => "menu-buttons" %>
    </div>
    <div class="left-button">
    <%= button_to "Employee Management", employeemanagement_path, method: :get,:class => "menu-buttons" %>
    </div>
    <div class="left-button">
    <%= button_to "Designation Management", designationmanagement_path, method: :get,:class => "menu-buttons" %>
    </div>
    <div class="left-button">
    <%= button_to "Project Management", projectmanagement_path, method: :get,:class => "menu-buttons" %>
    </div>
</div>

app/views/admin/adminhome.html.erb
<div class="adminmaincont">
<%= render "admin/adminmenu" %>
  <div class="leaves-main-cont">
    <h1 class="leave-head">Leaves</h1>
    <table class="table">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Edit</th>
    </tr>
<% @leave.each do |leav| %>
    <tr>
      <td>
      <%= leav.name%>
      </td>
      <td>
      <%= leav.description%>
      </td>
    <% end %>
  </table> 
  <%= button_to 'Add Leave', leaveform_path, method: :get,class:"employee-add-button"%>
    </div>
  </div>

app/views/admin/designationmanagement.html.erb
<div class="designation-main-cont">
<%= render "admin/adminmenu" %>
<div class="leaves-main-cont">
<h1 class="leave-head">Designation Management</h1>
<%= form_with model:@designation do  |f| %>
  <div class="field-form">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field-form">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
  </div>

<div class="actions">
  <%= f.submit "Save",class: "save-button" %>
</div>
<% end %>
</div>
</div>

app/views/admin/employeemanagement.html.erb
<div class="employeemanagement-main-cont">
<%= render "admin/adminmenu" %>
<div class="table-cont">
<h1 class="leave-head">Employee Management</h1>
<table class="table">
    <tr>
      <th>Name</th>
      <th>E Mail</th>
      <th>Employee Id</th>
    </tr>
<% @employees.each do |employee| %>
    <tr>
      <td>
      <%= employee.first_name+" "+employee.last_name%>
      </td>
      <td>
      <%= employee.email%>
      </td>
      <td>
      <%= employee.employee_unique_id%>
      </td>
    <% end %>
  </table> 
  <div>
  <%= button_to 'Add New Employee', new_employee_registration_path, method: :get,class:"employee-add-button"%>
  </div>
</div>
</div>

app/views/admin/leaveform.html.erb
<div class="designation-main-cont">
<%= render "admin/adminmenu" %>
<div class="designation-form-cont">
<h2>Add Leave</h2>
<%= form_with model:@leave do  |f| %>
  <div class="field-form">
      <%= f.label :name%><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field-form">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
  </div>

<div class="actions">
  <%= f.submit "Save",class: "save-button"%>
</div>
<% end %> 
</div>
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark">
<div class="navigation">
  <a class="navbar-brand ml-5" href="/">
    <img class="zensark-img" src="https://zensark.com/zensark2/wp-content/uploads/2021/01/Asset-16.png">
  </a>
  <% if current_employee %>
    <div class="profile-container">
      <p class="profile-name"><%= $name%></p>
      <div class="dropdown">
        <button class="round-button" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <%= $pname %>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><%= button_to "Adminstration", adminhome_path, class: " dropdown-item btn btn-secondary", method: :get%></li>
          <li><a class="dropdown-item" href="#">Manager</a></li>
          <li><%= button_to "Logout", destroy_employee_session_path, class: " dropdown-item btn btn-secondary", method: :delete%></li>
        </ul>
      </div>
    </div>
  <% else%>
  <% if request.path.split("/").last == 'sign_in' || request.path.split("/").last == 'sign_in?' %>
    <%= button_to "Home", root_path, class: "btn btn-warning", method: :get %>
  <% else %>
    <%= button_to "sign in", new_employee_session_path, class: "btn btn-warning mr-5", method: :get %>
  <% end%>
  <%end%>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    
      <%= yield %>
    
  </body>
</html>