config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  devise_for :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  get 'landing', to:"home#landing"
  get 'leave', to:"home#leave"





  #admin_routes
  get 'adminhome', to:"admin#adminhome"
  get 'employeemanagement', to: "admin#employeemanagement"
  
  
  get 'adminhome', to:"admin#adminhome"
  post 'leaveform', to: "admin#create"
  get 'leaveform', to:"admin#leaveform"
  
  get 'designationmanagement', to: "designation#designationmanagement"
  get 'designationform', to: "designation#designationform"
  post 'designationform', to: "designation#create"
 
  get 'projectmanagement', to: "project#projectmanagement"
  get 'projectform', to: "project#projectform"
  post 'projectform' ,to: "project#create"
  

  get 'holidaysmanagement', to: "holiday#holidaysmanagement"
  get 'holidaysform', to: "holiday#holidaysform"
  post 'holidaysform', to: "holiday#create"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/designation.rb
class Designation < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
end

app/models/employee_leave.rb
class EmployeeLeave < ApplicationRecord
end

app/models/employees_project.rb
class EmployeesProject < ApplicationRecord
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave.rb
class Leave < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/projects_management.rb
class ProjectsManagement < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new
    @leaves = Leave.new
  end
  def create
    @leaves= Leave.new(leavesparams)
    @leaves.save
    #render plain: @leaves.errors.inspect
    redirect_to adminhome_path
  end
  def leavesparams
    params.permit(:name , :description)
  end

  def employeemanagement
    @employees=Employee.all
  end
  def adminhome
    @leave = Leave.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :employee_unique_id, :role_id])
    end
    def after_sign_in_path_for(resource)
      if current_employee 
        landing_path
      else
        render root_path
      end
    end

    

end

app/controllers/holiday_controller.rb
class HolidayController < ApplicationController
  def new
    @holidays = Holiday.new
  end
  def create
    @holidays = Holiday.new(holidaysparams)
    @holidays.save
    #render plain: @holidays.errors.inspect
    redirect_to holidaysmanagement_path
  end
  
  def holidaysparams
    params.permit(:name, :date, :year)
  end

  def holidaysmanagement
    @holidays = Holiday.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def landing
    $name = full_name
    $pname = profile_name
  end

  
  def full_name
    user=Employee.find(current_employee.id)
    first_name = user.first_name
    last_name = user.last_name
    return first_name.capitalize+" "+last_name.capitalize
  end
  def profile_name
    user=Employee.find(current_employee.id)
    first_name = user.first_name
    last_name = user.last_name
    return first_name[0].capitalize+last_name[0].capitalize
  end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def new
    @project = Project.new
  end
  def create
    @project = Project.new(projectsparams)
    @project.save
    #render plain: @project.errors.inspect
    redirect_to projectmanagement_path
  end
  
  def projectsparams
    params.permit(:project_name, :client, :manager_id, :description, :client_time_zone, :shift_information, :project_type)
  end

  def projectmanagement
    @projects = Project.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designation_helper.rb
module DesignationHelper
end

app/helpers/holiday_helper.rb
module HolidayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/holiday/holidaysform.html.erb
<div class="designation-main-cont">
<%= render "admin/adminmenu" %>
<div class="designation-form-cont">
<h2>Add Holiday</h2>
<%= form_with model:@holiday do  |f| %>
  <div class="field-form">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field-form">
    <%= f.label :date %><br />
    <%= f.date_field :description, autofocus: true, autocomplete: "date" %>
  </div>

  <div class="field-form">
    <%= f.label :year %><br />
    <%= f.text_field :year, autofocus: true, autocomplete: "year" %>
  </div>

<div class="actions">
  <%= f.submit "Save",class: "save-button" %>
</div> 
<% end %>
</div>
</div> 

app/views/holiday/holidaysmanagement.html.erb
<div class="designation-main-cont">
<%= render "admin/adminmenu" %>
<div class="leaves-main-cont">
<h1 class="leave-head">Holiday Management</h1>
  <table class="table">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Edit</th>
      </tr>
  <% @holidays.each do |holiday| %>
      <tr>
        <td>
        <%= holiday.name%>
        </td>
        <td>
        <%= holiday.date%>
        </td>
      <% end %>
    </table> 
    <%= button_to "Add Holiday", holidaysform_path,method: :get,class: "save-button" %>
</div>
</div>

app/views/project/projectform.html.erb
<div class="designation-main-cont">
<%= render "admin/adminmenu" %>
<div class="designation-form-cont">
<h2>Add Project</h2>
<%= form_with model:@projects_management do  |f| %>
  <div class="field-form">
      <%= f.label :project_name %><br />
      <%= f.text_field :project_name, autofocus: true, autocomplete: "project_name" %>
  </div>

  <div class="field-form">
    <%= f.label :client %><br />
    <%= f.text_field :client, autofocus: true, autocomplete: "client" %>
  </div>

  <div class="field-form">
    <%= f.label :manager_id %><br />
    <%= f.text_field :manager_id, autofocus: true, autocomplete: "manager_id" %>
  </div>

  <div class="field-form">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
  </div>

  <div class="field-form">
    <%= f.label :client_time_zone %><br />
    <%= f.date_field :client_time_zone, autofocus: true, autocomplete: "client_time_zone" %>
  </div>

  <div class="field-form">
    <%= f.label :shift_information %><br />
    <%= f.text_field :shift_information, autofocus: true, autocomplete: "shift_information" %>
  </div>

  <div class="field-form">
    <%= f.label :project_type %><br />
    <%= f.text_field :project_type, autofocus: true, autocomplete: "project_type" %>
  </div>

<div class="actions">
  <%= f.submit "Save",class: "save-button" %>
</div> 
<% end %>
</div>
</div> 

app/views/project/projectmanagement.html.erb
<div class="designation-main-cont">
<%= render "admin/adminmenu" %>
<div class="leaves-main-cont">
<h1 class="leave-head">Project Management</h1>
  <table class="table">
      <tr>
        <th>Project_Name</th>
        <th>Description</th>
        <th>Edit</th>
      </tr>
  <% @projects.each do |project| %>
      <tr>
        <td>
        <%= project.project_name%>
        </td>
        <td>
        <%= project.description%>
        </td>
      <% end %>
    </table> 
    <%= button_to "Add Project", projectform_path,method: :get,class: "save-button" %>
</div>
</div>