config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  devise_for :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  get 'landing', to:"home#landing"
  get 'leave', to:"home#leave"





  #admin_routes
  get 'adminhome', to:"admin#adminhome"
  get 'employeemanagement', to: "admin#employeemanagement"
  
  
  get 'adminhome', to:"admin#adminhome"
  post 'leaveform', to: "admin#create"
  get 'leaveform', to:"admin#leaveform"
  
  get 'designationmanagement', to: "designation#designationmanagement"
  get 'designationform', to: "designation#designationform"
  post 'designationform', to: "designation#create"
 
  get 'projectmanagement', to: "project#projectmanagement"
  get 'projectform', to: "project#projectform"
  post 'projectform' ,to: "project#create"
  

  get 'holidaysmanagement', to: "holiday#holidaysmanagement"
  get 'holidaysform', to: "holiday#holidaysform"
  post 'holidaysform', to: "holiday#create"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/designation.rb
class Designation < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
end

app/models/employee_leave.rb
class EmployeeLeave < ApplicationRecord
end

app/models/employees_project.rb
class EmployeesProject < ApplicationRecord
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave.rb
class Leave < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/projects_management.rb
class ProjectsManagement < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new
    @leaves = Leave.new
  end
  def create
    @leaves= Leave.new(leavesparams)
    @leaves.save
    #render plain: @leaves.errors.inspect
    redirect_to adminhome_path
  end
  def leavesparams
    params.permit(:name , :description)
  end

  def employeemanagement
    @employees=Employee.all
  end
  def adminhome
    @leave = Leave.all
  end
end

app/controllers/holiday_controller.rb
class HolidayController < ApplicationController
  def new
    @holidays = Holiday.new
  end
  def create
    @holidays = Holiday.new(holidaysparams)
    @holidays.save
    #render plain: @holidays.errors.inspect
    redirect_to holidaysmanagement_path
  end
  
  def holidaysparams
    params.permit(:name, :date, :year)
  end

  def holidaysmanagement
    @holidays = Holiday.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def landing
    $name = full_name
    $pname = profile_name
  end

  
  def full_name
    user=Employee.find(current_employee.id)
    first_name = user.first_name
    last_name = user.last_name
    return first_name.capitalize+" "+last_name.capitalize
  end
  def profile_name
    user=Employee.find(current_employee.id)
    first_name = user.first_name
    last_name = user.last_name
    return first_name[0].capitalize+last_name[0].capitalize
  end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def new
    @project = Project.new
  end
  def create
    @project = Project.new(projectsparams)
    @project.save
    #render plain: @project.errors.inspect
    redirect_to projectmanagement_path
  end
  
  def projectsparams
    params.permit(:project_name, :client, :manager_id, :description, :client_time_zone, :shift_information, :project_type)
  end

  def projectmanagement
    @projects = Project.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designation_helper.rb
module DesignationHelper
end

app/helpers/holiday_helper.rb
module HolidayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/home/_leaveform.html.erb
<div class="formmaincont">
<div class="leave-top-cont">
<%= form_with model: @emplyee_leave do |f| %>
  
      <div class="field-form">
        <%= f.label :leave_id, "Leave Id"%><br />
        <%= f.number_field :leave_id, autofocus: true, autocomplete: "leave_id" %>
      </div>
      <div class="field-form">
        <%= f.label :emplyee_id, "Employe Id" %><br />
        <%= f.number_field :emplyee_id, autofocus: true, autocomplete: "emplyee-id" %>
      </div>

      <div class="field-form">
        <%= f.label :start_date%><br />
        <%= f.date_field :start_date, autofocus: true, autocomplete: "start_date" %>
      </div>

      <div class="field-form">
        <%= f.label :end_date %><br />
        <%= f.date_field :end_date, autofocus: true, autocomplete: "end_date" %>
      </div>
</div>
<div class="formbottomcont">
      <div class="field-form">
        <%= f.label :confirmed_by %><br />
        <%= f.text_field :confirmed_by, autofocus: true, autocomplete: "confirmed_by" %>
      </div>

      <div class="field-form">
        <%= f.label :status  %><br />
        <%= f.text_field :status, autofocus: true, autocomplete: "status" %>
      </div>

      <div class="field-form">
        <%= f.label :reason %><br />
        <%= f.text_area :reason, autofocus: true, autocomplete: "reason" %>
      </div>

  <div class="actions ">
    <%= f.submit "Add",class: "save-button" %>
  </div>
<% end %>
</div>
</div>

app/views/home/_menu.html.erb
<div class="left-container">
    <div class="left-button">
    <%= button_to "Dashboard", landing_path, method: :get,:class => "menu-buttons" %>
    </div>
    <div class="left-button">
    <%= button_to "Leave", leave_path, method: :get,:class => "menu-buttons" %>
    </div>
    <button class="left-button">
      Attendance
    </button>
    <button class="left-button">
      Settings
    </button>
</div>

app/views/home/index.html.erb
<div class="home-main-cont">
    <div class="home-sub-cont">
    <p class="home-para-1">Zensark is an agile technology services company, We bring together strong industry experience and deep technical expertise to help customers drive business value and revenue growth.</p> 

    <p>Zensark accords the highest priority to quality of software, and also the security of customer data.</p>
    
    <p>We understand your business and we are focused on meeting your needs and exceeding your expectations.</p>
    <% if current_employee %>
    <%= link_to "click here for dashboard", landing_path%>
    <% end %>
    </div>
</div>

app/views/home/landing.html.erb
<div class="main-container">
<%= render "home/menu" %>
  <div class="right-container">
    <div class="righttop-container">
      <div class="dash-container">
      <%= column_chart [["2021-01-01", 2], ["2021-01-02", 3],["2021-01-03", 4], ["2021-01-04", 5],["2021-01-05", 6], ["2021-01-06", 7],["2021-01-07", 8]], height: "216px" %>
      </div>
      <div class="heading-container">
        <h1 class="attendace-heading">Attendance Details</h1>
      </div>
    </div>
    <div class="rightbottom-container">
      <div class="rightbottom-left-container">
        <div class="upcoming-leaves-container">
        </div>
        <div class="heading-container">
          <h1 class="leaves-heading">Upcoming leaves</h1>
        </div>
      </div>
      <div class="rightbottom-right-container">
        <div>
        </div>
        <div class="heading-container">
          <h1 class="holidays-heading">Upcoming holidays</h1>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/leave.html.erb
<div class="leavemaincont">
  <%= render "home/menu" %>
  <div class="rightmain-cont">
    <div class="rightsubcont">
      <div class="right-cont">
        <div></div>
        <div class="heading-cont">
          <h5 >Total leaves</h5>
        </div>
      </div>
      <div class="right-cont">
        <div></div>
        <div class="heading-cont">
          <h5>Applied leaves</h5>
        </div>
      </div>
      <div class="right-cont">
        <div></div>
        <div class="heading-cont">
          <h5>Avaliable leaves</h5>
        </div>
      </div>
    </div>
    <div>
    <h2 class="leave-head">Apply Leave</h2>
    <%= render "home/leaveform" %>

    </div>
  </div>
</div>