config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  devise_for :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
  get 'landing', to:"home#landing"
  get 'leave', to:"home#leave"





  #admin_routes
  get 'adminhome', to:"admin#adminhome"
  get 'employeemanagement', to: "admin#employeemanagement"
  
  
  get 'adminhome', to:"admin#adminhome"
  post 'leaveform', to: "admin#create"
  get 'leaveform', to:"admin#leaveform"
  
  get 'designationmanagement', to: "designation#designationmanagement"
  get 'designationform', to: "designation#designationform"
  post 'designationform', to: "designation#create"
 
  get 'projectmanagement', to: "project#projectmanagement"
  get 'projectform', to: "project#projectform"
  post 'projectform' ,to: "project#create"
  

  get 'holidaysmanagement', to: "holiday#holidaysmanagement"
  get 'holidaysform', to: "holiday#holidaysform"
  post 'holidaysform', to: "holiday#create"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/designation.rb
class Designation < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
end

app/models/employee_leave.rb
class EmployeeLeave < ApplicationRecord
end

app/models/employees_project.rb
class EmployeesProject < ApplicationRecord
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave.rb
class Leave < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/projects_management.rb
class ProjectsManagement < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def new
    @leaves = Leave.new
  end
  def create
    @leaves= Leave.new(leavesparams)
    @leaves.save
    #render plain: @leaves.errors.inspect
    redirect_to adminhome_path
  end
  def leavesparams
    params.permit(:name , :description)
  end

  def employeemanagement
    @employees=Employee.all
  end
  def adminhome
    @leave = Leave.all
  end
end

app/controllers/designation_controller.rb
class DesignationController < ApplicationController
  def new
    @designations = Designation.new
  end
  def create
    @designations= Designation.new(designationsparams)
    @designations.save
    render plain: @designations.errors.inspect
    #redirect_to designation_path
    redirect_to designationmanagement_path
  end
  def designationsparams
    params.permit(:name , :description)
  end

  def designationmanagement
    @designations = Designation.all
  end
end

app/controllers/holiday_controller.rb
class HolidayController < ApplicationController
  def new
    @holidays = Holiday.new
  end
  def create
    @holidays = Holiday.new(holidaysparams)
    @holidays.save
    #render plain: @holidays.errors.inspect
    redirect_to holidaysmanagement_path
  end
  
  def holidaysparams
    params.permit(:name, :date, :year)
  end

  def holidaysmanagement
    @holidays = Holiday.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def landing
    $name = full_name
    $pname = profile_name
  end

  
  def full_name
    user=Employee.find(current_employee.id)
    first_name = user.first_name
    last_name = user.last_name
    return first_name.capitalize+" "+last_name.capitalize
  end
  def profile_name
    user=Employee.find(current_employee.id)
    first_name = user.first_name
    last_name = user.last_name
    return first_name[0].capitalize+last_name[0].capitalize
  end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def new
    @project = Project.new
  end
  def create
    @project = Project.new(projectsparams)
    @project.save
    #render plain: @project.errors.inspect
    redirect_to projectmanagement_path
  end
  
  def projectsparams
    params.permit(:project_name, :client, :manager_id, :description, :client_time_zone, :shift_information, :project_type)
  end

  def projectmanagement
    @projects = Project.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designation_helper.rb
module DesignationHelper
end

app/helpers/holiday_helper.rb
module HolidayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/designation/designationform.html.erb
<div class="designation-main-cont">
<%= render "admin/adminmenu" %>
<div class="designation-form-cont">
<h2>Add Desigantion</h2>
<%= form_with model:@designation do  |f| %>
  <div class="field-form">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field-form">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
  </div>

<div class="actions">
  <%= f.submit "Save",class: "save-button" %>
</div> 
<% end %>
</div>
</div> 

app/views/designation/designationmanagement.html.erb
<div class="designation-main-cont">
<%= render "admin/adminmenu" %>
<div class="leaves-main-cont">
<h1 class="leave-head">Designation Management</h1>
  <table class="table">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Edit</th>
      </tr>
  <% @designations.each do |designation| %>
      <tr>
        <td>
        <%= designation.name%>
        </td>
        <td>
        <%= designation.description%>
        </td>
      <% end %>
    </table> 
    <%= button_to "Add Designation", designationform_path,method: :get,class: "save-button" %>
</div>
</div>